[profile.default]
  optimizer = true
  optimizer_runs = 10_000_000
  solc_version = "0.8.17"
  verbosity = 3

[profile.ci]
  fuzz = { runs = 500 }
  invariant = { runs = 500 }

[profile.lite]
  fuzz = { runs = 50, seed = 1673481600 }
  invariant = { runs = 10 }
  # Speed up compilation and tests during development.
  optimizer = false

[rpc_endpoints]
  mainnet = "${MAINNET_RPC_URL}"

[fmt]
  bracket_spacing = false
  int_types = "long"
  line_length = 100
  multiline_func_header = "attributes_first"
  number_underscore = "thousands"
  quote_style = "double"
  single_line_statement_blocks = "single"
  tab_width = 2
  wrap_comments = true
